[package]
name = "ai-agent-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.92"
async-openai = "0.25.0"
qdrant-client = "1.12.1"
tokio = { version = "1.41.0", features = ["full"] }
