model_list:
  # - model_name: gpt-3.5-turbo
  #   litellm_params:
  #     model: gemini/gemini-1.5-flash
  #     api_key: os.environ/GEMINI_API_KEY
  #
  # - model_name: text-embedding-3-small
  #   litellm_params:
  #     model: gemini/text-embedding-004
  #     api_key: os.environ/GEMINI_API_KEY

  - model_name: gpt-3.5-turbo
    litellm_params:
      model: groq/llama-3.2-3b-preview
      api_key: os.environ/GROQ_API_KEY

  - model_name: text-embedding-3-small
    litellm_params:
      model: openai/jina-embeddings-v3
      api_base: https://api.jina.ai/v1
      api_key: os.environ/JINA_API_KEY

litellm_settings:
  drop_params: True
